apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: mlflow
 namespace: infra-tools
spec:
 project: default
 source:
  repoURL: https://community-charts.github.io/helm-charts
  chart: mlflow
  targetRevision: 1.6.2
  helm:
   releaseName: mlflow
   valuesObject:
    service:
     type: ClusterIP
     port: 5000

    auth:
     enabled: false

    postgresql:
     enabled: true
     primary:
      persistence:
       enabled: true
       existingClaim: mlflow-postgresql-data
     auth:
      postgresPassword: mlflowpass
      username: mlflow
      password: mlflowpass
      database: mlflowdb

 destination:
  namespace: application
  server: https://kubernetes.default.svc

 syncPolicy:
  automated:
   prune: true
   selfHeal: true
  syncOptions:
   - ServerSideApply=true
   - SkipDryRunOnMissingResource=true